### ISSUE TITLE
scipy requirement

### ISSUE THREAD

**Issue by AshKelly** [syasini/AstroPaint#80]
I'm just wondering if there is for specifying such an old version of scipy?
```
scipy==1.3.0
```
This `scipy` release appears to be over a year old, and from some minor experimentation locally `AstroPaint` works perfectly with later versions of `scipy` (even the latest version).

There are actually a few hardcoded version numbers, which could maybe be relaxed, slightly.

**Comment by syasini** [comment]
Thanks for pointing this out @AshKelly. 

There is not specific reason for this. Initially the `==` was used for all the requirements in the package to make sure the installation is consistent over various environments during testing and to avoid conflicts due to possibly deprecated methods in future versions of numpy, scipy ,etc. But I don't have a strong preference for things remaining this way. 

should I change the version requirements to `>=` instead to relax the constraints as you suggested?

**Comment by AshKelly** [comment]
> Thanks for pointing this out @AshKelly.
> 
> There is not specific reason for this. Initially the `==` was used for all the requirements in the package to make sure the installation is consistent over various environments during testing and to avoid conflicts due to possibly deprecated methods in future versions of numpy, scipy ,etc. But I don't have a strong preference for things remaining this way.

That's entirely reasonable. I think for larger, more static libraries like `numpy` and `scipy` you don't need to be as strict with an exact version. In general, we get plenty of warning when their API is changing. In my use case, having `==` actually caused me quite an inconvenience within my usual astro python enviro where I had newer versions installed. 

I don't have particularly strong opinions about this, so I'll yield to your judgement, as you know the user base of your library better. I was just slightly surprised by the age of the `scipy` requirement.

**Comment by syasini** [comment]
That makes perfect sense. I changed the `==` in `requirements.txt` to `>=` for all the packages with the exception of `healpy`. I personally ran into issues installing the latest release `1.14` so I'm keeping the `1.13` dependency in AstroPaint for now. A lot of new installations typically fail because of healpy, so I'm just playing it safe until `1.14` becomes stable. 

Feel free to close the issue.
